// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAsyydY6CfeKirzgWi6Z8aTs0PUhtV6zxY',
    appId: '1:546808553796:web:60f6aec96a29031c6cf711',
    messagingSenderId: '546808553796',
    projectId: 'safespace-6039f',
    authDomain: 'safespace-6039f.firebaseapp.com',
    storageBucket: 'safespace-6039f.firebasestorage.app',
    measurementId: 'G-BSS9C5HVKY',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAUX1jcX0zNYCgENH3DWderMAP-B2H8ptM',
    appId: '1:546808553796:android:865e206b31da56706cf711',
    messagingSenderId: '546808553796',
    projectId: 'safespace-6039f',
    storageBucket: 'safespace-6039f.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAhb2zL21pL_vgaE6nysP-kiYwFZzKrhWY',
    appId: '1:546808553796:ios:be175dec323ea8e96cf711',
    messagingSenderId: '546808553796',
    projectId: 'safespace-6039f',
    storageBucket: 'safespace-6039f.firebasestorage.app',
    iosBundleId: 'com.example.safespace',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAhb2zL21pL_vgaE6nysP-kiYwFZzKrhWY',
    appId: '1:546808553796:ios:be175dec323ea8e96cf711',
    messagingSenderId: '546808553796',
    projectId: 'safespace-6039f',
    storageBucket: 'safespace-6039f.firebasestorage.app',
    iosBundleId: 'com.example.safespace',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAsyydY6CfeKirzgWi6Z8aTs0PUhtV6zxY',
    appId: '1:546808553796:web:3f0c7986744926a16cf711',
    messagingSenderId: '546808553796',
    projectId: 'safespace-6039f',
    authDomain: 'safespace-6039f.firebaseapp.com',
    storageBucket: 'safespace-6039f.firebasestorage.app',
    measurementId: 'G-NDLMVMRC12',
  );

}